affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 2
symbolic.funs_name.0:
- - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - log
  - x^2
  - x^2
  - 1/x
  - log
  - x^2
  - x^2
  - x^2
  - sin
  - x^2
  - x^2
  - sin
  - x^2
  - x^2
  - x^2
  - x^2
  - exp
  - x^2
  - x^2
  - sin
  - x^2
  - sin
  - x^2
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - sin
  - x^2
  - x^2
  - x^2
  - exp
  - x^2
  - log
  - log
  - x^2
  - x^2
  - x^2
  - sin
  - x^2
  - x^2
  - sin
  - exp
  - sin
  - x^2
  - x^2
  - x^2
  - sin
  - x^2
  - sin
  - x^2
  - sin
  - x^2
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - sin
  - log
  - x^2
  - log
  - x^2
  - exp
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - sin
  - x^2
  - x^2
  - sin
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - sin
  - x^2
  - sin
  - x^2
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x
  - sin
  - x
  - sin
  - sin
  - sin
  - sin
  - x^2
  - sin
  - x
  - exp
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - sin
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - sin
  - sin
  - x^2
  - log
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - x^2
  - sin
  - x^2
  - x^2
  - sin
  - x^2
  - sin
  - sin
  - x^2
  - x^2
  - x^2
  - x^2
  - log
  - x^2
  - sin
  - sin
  - x^2
  - x^2
  - x^2
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
symbolic.funs_name.1:
- - x
  - x
  - x
  - x
  - x
symbolic_enabled: true
width:
- - 71
  - 0
- - 5
  - 0
- - 1
  - 0
